package net.icxd.dungeons.item.enums;

public enum SpecificItemType {
    REFORGE_STONE,
    SWORD,
    BOOTS,
    BELT,
    NECKLACE,
    GLOVES,
    HELMET,
    CHESTPLATE,
    ACCESSORY,
    CLOAK,
    LEGGINGS,
    AXE,
    HOE,
    COSMETIC,
    PET_ITEM,
    BAIT,
    FISHING_ROD,
    PORTAL,
    BOW,
    NONE,
    WAND,
    DUNGEON_PASS,
    ARROW,
    SPADE,
    PICKAXE,
    DEPLOYABLE,
    DRILL,
    SHEARS,
    BRACELET,
    GAUNTLET,
    LONGSWORD,
    TRAVEL_SCROLL,
    ARROW_POISON,
    FISHING_WEAPON
}
