package net.icxd.dungeons.item.items;

import net.icxd.dungeons.crimsonisle.kuudra.KuudraTier;
import net.icxd.dungeons.item.SkyBlockItem;
import net.icxd.dungeons.item.cost.UpgradeCost;
import net.icxd.dungeons.item.cost.UpgradeCosts;
import net.icxd.dungeons.item.cost.essence.EssenceCost;
import net.icxd.dungeons.item.cost.essence.EssenceType;
import net.icxd.dungeons.item.cost.item.ItemCost;
import net.icxd.dungeons.item.enums.Rarity;
import net.icxd.dungeons.item.enums.SpecificItemType;
import net.icxd.dungeons.item.gemstone.GemstoneSlot;
import net.icxd.dungeons.item.gemstone.GemstoneSlots;
import net.icxd.dungeons.item.requirement.KuudraTierRequirement;
import net.icxd.dungeons.item.requirement.Requirements;
import net.icxd.dungeons.item.requirement.skill.SkillRequirement;
import net.icxd.dungeons.skill.Skill;
import net.icxd.dungeons.stats.Stats;
import net.icxd.dungeons.utils.Utils;
import org.bukkit.Color;
import org.bukkit.Material;

import java.util.ArrayList;
import java.util.List;

import static net.icxd.dungeons.stats.Stat.CRIT_DAMAGE;
import static net.icxd.dungeons.stats.Stat.DEFENSE;
import static net.icxd.dungeons.stats.Stat.HEALTH;
import static net.icxd.dungeons.stats.Stat.INTELLIGENCE;
import static net.icxd.dungeons.stats.Stat.STRENGTH;

/**
 * Kuudra's Crimson armor: four pieces in five tiers, Crimson to Infernal. Stats and text are
 * Hypixel's (the NEU item repository's dumps); the star costs are this plugin's.
 * Generated by tools/items/gen_tables.py, apart from the code under the tier table.
 */
public final class CrimsonArmor {
    private CrimsonArmor() {
    }

    enum Tier {
        BASIC("", "", KuudraTier.BASIC, 22, "5051c83d9ebf69013f1ec8c9efc979ec2d925a921cc877ff64abe09aadd2f6cc",
                List.of("&8Tiered Bonus: Dominus (0/4)",
                    "&7Every &a1.5s&7, melee attacks grant &c1&7 stack of",
                    "&6ᝐ Dominus&7. &8Lose 1 stack after 4s of not",
                    "&8gaining a stack.",
                    "",
                    "&7Each stack grants &e+0.05Ⓢ Swing Range&7.",
                    "",
                    "&7At &c10&7 stacks swipe in a random direction",
                    "&7dealing &c0.5x &4Swipe Damage&7 to mobs in its path."),
                List.of(star(30), star(35), star(40), star(45), star(50), star(55), star(60), star(70, 2), star(80, 3), star(90, 4)),
                new Stats().set(HEALTH, 160).set(DEFENSE, 50).set(STRENGTH, 30).set(CRIT_DAMAGE, 20).set(INTELLIGENCE, 15),
                new Stats().set(HEALTH, 230).set(DEFENSE, 65).set(STRENGTH, 30).set(CRIT_DAMAGE, 20).set(INTELLIGENCE, 5),
                new Stats().set(HEALTH, 205).set(DEFENSE, 55).set(STRENGTH, 30).set(CRIT_DAMAGE, 20).set(INTELLIGENCE, 5),
                new Stats().set(HEALTH, 130).set(DEFENSE, 40).set(STRENGTH, 30).set(CRIT_DAMAGE, 20).set(INTELLIGENCE, 5)),
        HOT("Hot ", "HOT_", KuudraTier.HOT, 27, "bbe6d66770a61bf56e6d4b476922b1c3b3dc9f78a26e56b36cd965b7ab20b417",
                List.of("&8Tiered Bonus: Dominus (0/4)",
                    "&7Every &a1.5s&7, melee attacks grant &c1&7 stack of",
                    "&6ᝐ Dominus&7. &8Lose 1 stack after 4s of not",
                    "&8gaining a stack.",
                    "",
                    "&7Each stack grants &e+0.1Ⓢ Swing Range&7.",
                    "",
                    "&7At &c10&7 stacks swipe in a random direction",
                    "&7dealing &c0.62x &4Swipe Damage&7 to mobs in its",
                    "&7path."),
                List.of(star(170), star(190), star(215), star(240), star(270), star(300), star(340), star(390, 3), star(440, 4), star(500, 5)),
                new Stats().set(HEALTH, 202).set(DEFENSE, 63).set(STRENGTH, 38).set(CRIT_DAMAGE, 25).set(INTELLIGENCE, 19),
                new Stats().set(HEALTH, 290).set(DEFENSE, 82).set(STRENGTH, 38).set(CRIT_DAMAGE, 25).set(INTELLIGENCE, 6),
                new Stats().set(HEALTH, 258).set(DEFENSE, 69).set(STRENGTH, 38).set(CRIT_DAMAGE, 25).set(INTELLIGENCE, 6),
                new Stats().set(HEALTH, 164).set(DEFENSE, 50).set(STRENGTH, 38).set(CRIT_DAMAGE, 25).set(INTELLIGENCE, 6)),
        BURNING("Burning ", "BURNING_", KuudraTier.BURNING, 32, "eb034a5d97c24fe0ec902bd02fec52a09d917366be060c51f9a1a276b284a9d7",
                List.of("&8Tiered Bonus: Dominus (0/4)",
                    "&7Every &a1.5s&7, melee attacks grant &c1&7 stack of",
                    "&6ᝐ Dominus&7. &8Lose 1 stack after 4s of not",
                    "&8gaining a stack.",
                    "",
                    "&7Each stack grants &e+0.1Ⓢ Swing Range",
                    "&7and &c+1⫽ Ferocity&7.",
                    "",
                    "&7At &c10&7 stacks swipe in a random direction",
                    "&7dealing &c0.75x &4Swipe Damage&7 to mobs in its",
                    "&7path."),
                List.of(star(900), star(1000), star(1125), star(1270), star(1450), star(1650), star(1850), star(2100, 3), star(2350, 4), star(2650, 5)),
                new Stats().set(HEALTH, 254).set(DEFENSE, 79).set(STRENGTH, 48).set(CRIT_DAMAGE, 32).set(INTELLIGENCE, 24),
                new Stats().set(HEALTH, 365).set(DEFENSE, 103).set(STRENGTH, 48).set(CRIT_DAMAGE, 32).set(INTELLIGENCE, 8),
                new Stats().set(HEALTH, 325).set(DEFENSE, 87).set(STRENGTH, 48).set(CRIT_DAMAGE, 32).set(INTELLIGENCE, 8),
                new Stats().set(HEALTH, 206).set(DEFENSE, 64).set(STRENGTH, 48).set(CRIT_DAMAGE, 32).set(INTELLIGENCE, 8)),
        FIERY("Fiery ", "FIERY_", KuudraTier.FIERY, 37, "91f0c7afff1782465d8cdb5eba261b65423a7a0712ee3a4c572c33f94c68c55",
                List.of("&8Tiered Bonus: Dominus (0/4)",
                    "&7Every &a1.5s&7, melee attacks grant &c1&7 stack of",
                    "&6ᝐ Dominus&7. &8Lose 1 stack after 4s of not",
                    "&8gaining a stack.",
                    "",
                    "&7Each stack grants &e+0.1Ⓢ Swing Range",
                    "&7and &c+2⫽ Ferocity&7.",
                    "",
                    "&7At &c10&7 stacks swipe in a random direction",
                    "&7dealing &c0.88x &4Swipe Damage&7 to mobs in its",
                    "&7path."),
                List.of(star(5000), star(5600), star(6300), star(7000), star(8000), star(9000), star(10200), star(11500, 3), star(13000, 4), star(14500, 5)),
                new Stats().set(HEALTH, 320).set(DEFENSE, 100).set(STRENGTH, 60).set(CRIT_DAMAGE, 40).set(INTELLIGENCE, 30),
                new Stats().set(HEALTH, 460).set(DEFENSE, 130).set(STRENGTH, 60).set(CRIT_DAMAGE, 40).set(INTELLIGENCE, 10),
                new Stats().set(HEALTH, 410).set(DEFENSE, 110).set(STRENGTH, 60).set(CRIT_DAMAGE, 40).set(INTELLIGENCE, 10),
                new Stats().set(HEALTH, 260).set(DEFENSE, 80).set(STRENGTH, 60).set(CRIT_DAMAGE, 40).set(INTELLIGENCE, 10)),
        INFERNAL("Infernal ", "INFERNAL_", KuudraTier.INFERNAL, 42, "507d6bf7611190ed9c580d8c87c296059216230c9501eec6359e0d60ec84758e",
                List.of("&8Tiered Bonus: Dominus (0/4)",
                    "&7Every &a1.5s&7, melee attacks grant &c1&7 stack of",
                    "&6ᝐ Dominus&7. &8Lose 1 stack after 4s of not",
                    "&8gaining a stack.",
                    "",
                    "&7Each stack grants &e+0.1Ⓢ Swing Range&7,",
                    "&c+2⫽ Ferocity&7 and &c+10% Damage&7.",
                    "",
                    "&7At &c10&7 stacks swipe in a random direction",
                    "&7dealing &c1x &4Swipe Damage&7 to mobs in its path."),
                List.of(star(30000), star(35000), star(41000), star(48000), star(56000), star(65500), star(76000), star(89000, 3), star(105000, 4), star(120000, 5), star(140000, 6), star(165000, 7), star(192000, 8), star(225000, 9), star(265000, 10)),
                new Stats().set(HEALTH, 403).set(DEFENSE, 126).set(STRENGTH, 76).set(CRIT_DAMAGE, 50).set(INTELLIGENCE, 38),
                new Stats().set(HEALTH, 580).set(DEFENSE, 164).set(STRENGTH, 76).set(CRIT_DAMAGE, 50).set(INTELLIGENCE, 13),
                new Stats().set(HEALTH, 517).set(DEFENSE, 139).set(STRENGTH, 76).set(CRIT_DAMAGE, 50).set(INTELLIGENCE, 13),
                new Stats().set(HEALTH, 328).set(DEFENSE, 101).set(STRENGTH, 76).set(CRIT_DAMAGE, 50).set(INTELLIGENCE, 13));

        final String prefix;
        final String idPrefix;
        final KuudraTier kuudra;
        final int combatLevel;
        final String helmetTexture;
        /** The Dominus tiered bonus, as each piece of the tier shows it. */
        final List<String> bonus;
        final List<UpgradeCost> stars;
        final List<Stats> stats;

        Tier(String prefix, String idPrefix, KuudraTier kuudra, int combatLevel, String helmetTexture, List<String> bonus,
             List<UpgradeCost> stars, Stats helmet, Stats chestplate, Stats leggings, Stats boots) {
            this.prefix = prefix;
            this.idPrefix = idPrefix;
            this.kuudra = kuudra;
            this.combatLevel = combatLevel;
            this.helmetTexture = helmetTexture;
            this.bonus = bonus;
            this.stars = stars;
            this.stats = List.of(helmet, chestplate, leggings, boots);
        }
    }

    enum Piece {
        HELMET("Helmet", Material.PLAYER_HEAD, SpecificItemType.HELMET, null),
        CHESTPLATE("Chestplate", Material.LEATHER_CHESTPLATE, SpecificItemType.CHESTPLATE, Color.fromRGB(0xFF6F0C)),
        LEGGINGS("Leggings", Material.LEATHER_LEGGINGS, SpecificItemType.LEGGINGS, Color.fromRGB(0xE66105)),
        BOOTS("Boots", Material.LEATHER_BOOTS, SpecificItemType.BOOTS, Color.fromRGB(0xE65300));

        final String name;
        final Material material;
        final SpecificItemType type;
        final Color color;

        Piece(String name, Material material, SpecificItemType type, Color color) {
            this.name = name;
            this.material = material;
            this.type = type;
            this.color = color;
        }
    }

    public static List<SkyBlockItem> all() {
        List<SkyBlockItem> items = new ArrayList<>();
        for (Tier tier : Tier.values()) for (Piece piece : Piece.values()) items.add(new Item(tier, piece));
        return items;
    }

    private static UpgradeCost star(int essence) {
        return new UpgradeCost(new EssenceCost(EssenceType.CRIMSON, essence));
    }

    private static UpgradeCost star(int essence, int heavyPearls) {
        return new UpgradeCost(new EssenceCost(EssenceType.CRIMSON, essence), new ItemCost("HEAVY_PEARL", heavyPearls));
    }


    private record Item(Tier tier, Piece piece) implements SkyBlockItem {
        @Override public String id() { return tier.idPrefix + "CRIMSON_" + piece.name(); }
        @Override public String name() { return tier.prefix + "Crimson " + piece.name; }
        @Override public Material material() { return piece.material; }
        @Override public Rarity rarity() { return Rarity.LEGENDARY; }
        @Override public String skin() { return piece == Piece.HELMET ? Utils.texture(tier.helmetTexture) : null; }
        @Override public Color color() { return piece.color; }
        @Override public SpecificItemType specificItemType() { return piece.type; }
        @Override public Stats stats() { return tier.stats.get(piece.ordinal()).copy(); }
        @Override public GemstoneSlots gemstoneSlots() { return new GemstoneSlots(GemstoneSlot.combat(), GemstoneSlot.combat()); }
        @Override public List<String> lore() { return tier.bonus; }
        @Override public Requirements requirements() {
            return new Requirements(new SkillRequirement(Skill.COMBAT, tier.combatLevel), new KuudraTierRequirement(tier.kuudra));
        }
        @Override public UpgradeCosts upgradeCosts() { return new UpgradeCosts(tier.stars.toArray(UpgradeCost[]::new)); }
        @Override public boolean canHaveAttributes() { return true; }
    }
}
