package net.icxd.dungeons.item.items;

import net.icxd.dungeons.item.SkyBlockItem;
import net.icxd.dungeons.item.enums.Rarity;
import net.icxd.dungeons.item.enums.SpecificItemType;
import net.icxd.dungeons.item.gemstone.GemstoneType;
import net.icxd.dungeons.utils.Utils;
import org.bukkit.Material;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The 40 gemstones: each of the eight gemstone types at each of the five qualities, as Hypixel shows
 * them (text from the NEU item repository's dumps, head textures from this plugin's old items).
 * Generated by tools/items/gen_tables.py, apart from the code under the table.
 */
public final class Gemstones {
    private Gemstones() {
    }

    /** Rarity and NPC sell price by quality. */
    enum Quality {
        ROUGH("Rough", Rarity.COMMON, 3),
        FLAWED("Flawed", Rarity.UNCOMMON, 240),
        FINE("Fine", Rarity.RARE, 19_200),
        FLAWLESS("Flawless", Rarity.EPIC, 1_536_000),
        PERFECT("Perfect", Rarity.LEGENDARY, 10_240_000);

        final String name;
        final Rarity rarity;
        final double sellPrice;

        Quality(String name, Rarity rarity, double sellPrice) {
            this.name = name;
            this.rarity = rarity;
            this.sellPrice = sellPrice;
        }
    }

    /** The eight types there are gemstones of, and the stat each gives ("extra ❤ Health"). */
    private static final Map<GemstoneType, String> STAT = Map.of(
            GemstoneType.RUBY, "&c❤ Health", GemstoneType.AMETHYST, "&a❈ Defense", GemstoneType.JADE, "&6☘ Mining Fortune",
            GemstoneType.SAPPHIRE, "&b✎ Intelligence", GemstoneType.AMBER, "&6⸕ Mining Speed", GemstoneType.TOPAZ, "&5✧ Pristine",
            GemstoneType.JASPER, "&c❁ Strength", GemstoneType.OPAL, "&f❂ True Defense");

    private record Text(String texture, List<String> intro) {
    }

    private static final Map<String, Text> TEXT = new HashMap<>();

    private static void entry(String id, String texture, String... intro) {
        TEXT.put(id, new Text(texture, List.of(intro)));
    }

    static {
        entry("ROUGH_RUBY_GEM", "d159b03243be18a14f3eae763c4565c78f1f339a8742d26fde541be59b7de07", "&7Harvested from the plentiful", "&7gemstone veins in the &5Crystal Hollows&7.");
        entry("FLAWED_RUBY_GEM", "46d81068cbdf4a364231a26453d6cd660a0095f9cd8795307c5be667427712e", "&7A slightly better version of &cRuby&7,", "&7but it could still use some work.");
        entry("FINE_RUBY_GEM", "e672959028f274b379d430f068f0f15a4f793eac12afb94ae0b4e50cf895df0f", "&7A type of &cRuby &7that has clearly", "&7been treated with care.");
        entry("FLAWLESS_RUBY_GEM", "926a248fbbc06cf06e2c920eca1cac8a2c96164d3260494bed142d553026cc6", "&7A near perfect version of &cRuby&7.");
        entry("PERFECT_RUBY_GEM", "39b6e047d3b2bca85e8cc49e5480f9774d8a0eafe6dfa9559530590283715142", "&7A perfectly &crefined Ruby&7.");
        entry("ROUGH_AMETHYST_GEM", "e493c6f540c7001fed97b07f6b4c89128e3a7c37563aa223f0acca314f175515", "&7Harvested from the plentiful", "&7gemstone veins in the &5Crystal Hollows&7.");
        entry("FLAWED_AMETHYST_GEM", "71db59260895578d37e59505880602de940b088e5fff8da3e65201d739c86e84", "&7A slightly better version of", "&5Amethyst&7, but it could still use some", "&7work.");
        entry("FINE_AMETHYST_GEM", "7a1ee5ffce04eb7da592d42414ff35e1bf38194d6b82e310dbc6261b47fb9c91", "&7A type of &5Amethyst &7that has clearly", "&7been treated with care.");
        entry("FLAWLESS_AMETHYST_GEM", "d3623521c8111ad29e9dcf7acc56085a9ab07da732d1518976aee61d0b3e3bd6", "&7A near perfect version of &5Amethyst&7.");
        entry("PERFECT_AMETHYST_GEM", "d886e0f41185b18a3afd89488d2ee4caa0735009247cccf039ced6aed752ff1a", "&7A perfectly &5refined Amethyst&7.");
        entry("ROUGH_JADE_GEM", "3b4c2afd544d0a6139e6ae8ef8f0bfc09a9fd837d0cad4f5cd0fe7f607b7d1a0", "&7Harvested from the plentiful", "&7gemstone veins in the &5Crystal Hollows&7.");
        entry("FLAWED_JADE_GEM", "82282c6bb8343e0f0d61ee0747dada75344f332e9ff0acaa3adcdf09321d3dd", "&7A slightly better version of &aJade&7,", "&7but it could still use some work.");
        entry("FINE_JADE_GEM", "b28f1c0c5092e12d33770df45c5845a9610886039b34abe93a16c5e942dfc8e4", "&7A type of &aJade &7that has clearly", "&7been treated with care.");
        entry("FLAWLESS_JADE_GEM", "f89f75e0b00378a583dbba728dcdc6e9346f31dd601d448f3d60615c7465cc3e", "&7A near perfect version of &aJade&7.");
        entry("PERFECT_JADE_GEM", "3fced7977382bf71d4ee17ff5b919e0eb7972083c4cccfa175c8753ae40ba006", "&7A perfectly &arefined Jade&7.");
        entry("ROUGH_SAPPHIRE_GEM", "cfcebe54dbc345ea7e22206f703e6b33befbe95b6a918bd1754b76188bc65bb5", "&7Harvested from the plentiful", "&7gemstone veins in the &5Crystal Hollows&7.");
        entry("FLAWED_SAPPHIRE_GEM", "8a0af99e8d8703194a847a55268cf5ef4ac4eb3b24c0ed86551339d10b646529", "&7A slightly better version of", "&bSapphire&7, but it could still use some", "&7work.");
        entry("FINE_SAPPHIRE_GEM", "36161daa3589ec9c8187459ac36fd4dd2646c040678d3bfacb72a2210c6c801c", "&7A type of &bSapphire &7that has clearly", "&7been treated with care.");
        entry("FLAWLESS_SAPPHIRE_GEM", "957cfa9c75ba584645ee2af6d9867d767ddea4667cdfc72dc1061dd1975ca7d0", "&7A near perfect version of &bSapphire&7.");
        entry("PERFECT_SAPPHIRE_GEM", "8e93ebacb60b71793355fde0d4bba43a9c5ec09c3f38897c48c1f857523a0a29", "&7A perfectly &brefined Sapphire&7.");
        entry("ROUGH_AMBER_GEM", "da19436f6151a7b66d65ed7624add4325cfbbc2eee815fcf76f4c29ddf08f75b", "&7Harvested from the plentiful", "&7gemstone veins in the &5Crystal Hollows&7.");
        entry("FLAWED_AMBER_GEM", "173bcfc39eb85df1848535985214060a1bd1b3bb47defe4201476edc31671744", "&7A slightly better version of &6Amber&7,", "&7but it could still use some work.");
        entry("FINE_AMBER_GEM", "4b1cce22de19ed6727abc5e6c2d57864c871a44c956bbe2eb3960269b686b8b3", "&7A type of &6Amber &7that has clearly", "&7been treated with care.");
        entry("FLAWLESS_AMBER_GEM", "9dce62f70ac046b881113c6cf862987727774e265885501c9a245b180db08c0d", "&7A near perfect version of &6Amber&7.");
        entry("PERFECT_AMBER_GEM", "37ae236cdec3f2a6f51eae15e2c8f6228b34f137da1569fec9e803f9cd81759d", "&7A perfectly &6refined Amber&7.");
        entry("ROUGH_TOPAZ_GEM", "3fd960722ec29c66716ae5ca97b9b6b2628984e1d6f9d2592cd089914206a1b", "&7Harvested from the plentiful", "&7gemstone veins in the &5Crystal Hollows&7.");
        entry("FLAWED_TOPAZ_GEM", "b6392773d114be30aeb3c09c90cbe691ffeaceb399b530fe6fb53ddc0ced3714", "&7A slightly better version of &eTopaz&7,", "&7but it could still use some work.");
        entry("FINE_TOPAZ_GEM", "92cb6e51c461e7359526bea5e06209cddde7c6469a819f3405cf0a038c159502", "&7A type of &eTopaz &7that has clearly", "&7been treated with care.");
        entry("FLAWLESS_TOPAZ_GEM", "d10964f3c479ad7d9afaf68a42cab7c107d2d884f575cae2f070ec6f935b3be", "&7A near perfect version of &eTopaz&7.");
        entry("PERFECT_TOPAZ_GEM", "3da6ecdcbc3fe355ca0611192a3fbd35dd5635d5fcdf3fbc79ed2bc1f4a017fe", "&7A perfectly &erefined Topaz&7.");
        entry("ROUGH_JASPER_GEM", "23d064ec150172d05844c11a18619c1421bbfb2ddd1dbb87cdc10e22252b773b", "&7Harvested from the plentiful", "&7gemstone veins in the &5Crystal Hollows&7.");
        entry("FLAWED_JASPER_GEM", "a73511e504c316b139edb35febe73ef591c0f455e8caf9ee353bc12b6c14a922", "&7A slightly better version of &dJasper&7,", "&7but it could still use some work.");
        entry("FINE_JASPER_GEM", "aac15f6fcf2ce963ef4ca71f1a8685adb97eb769e1d11194cbbd2e964a88978c", "&7A type of &dJasper &7that has clearly", "&7been treated with care.");
        entry("FLAWLESS_JASPER_GEM", "ff993d3a43d40597b474485976160d0cf52ac64d157307d3b1c941db224d0ac6", "&7A near perfect version of &dJasper&7.");
        entry("PERFECT_JASPER_GEM", "263f991b8e038e46b8ed7632f44ca2e30c15f42977070a8c8d8728e3fc04fc7c", "&7A perfectly &drefined Jasper&7.");
        entry("ROUGH_OPAL_GEM", "a14d3c57f80824b3839b8b220f2158bca505d497fd1c9e3f29f422b1e6206a45", "&7Found sprinkled around the &cCrimson", "&cIsle&7.");
        entry("FLAWED_OPAL_GEM", "eadc3bcdd7c701b63f8b8b4a96e429316a08388669d9a98c1a98791729b961df", "&7A slightly better version of &fOpal&7, but", "&7it could still use some work.");
        entry("FINE_OPAL_GEM", "ad798e20a47d251a9e33d40332973c7189ac1550760ba25c4b956c9159364568", "&7A type of &fOpal &7that has clearly been", "&7treated with care.");
        entry("FLAWLESS_OPAL_GEM", "5d15ed70e720040ad7311e69359dfdf5e114eadd2a4c1f971a9501341a45264b", "&7A near perfect version of &fOpal&7.");
        entry("PERFECT_OPAL_GEM", "7e509f06b8dc384358ff2472ab62ce6fdc2f646e338efdc3c9fb05ddc431f64", "&7A perfectly &frefined Opal&7.");
    }

    public static List<SkyBlockItem> all() {
        List<SkyBlockItem> items = new ArrayList<>();
        for (GemstoneType type : STAT.keySet()) for (Quality quality : Quality.values()) items.add(new Gem(type, quality));
        items.sort(java.util.Comparator.comparing(SkyBlockItem::id));
        return items;
    }

    private record Gem(GemstoneType type, Quality quality) implements SkyBlockItem {
        @Override public String id() { return quality.name() + "_" + type.name() + "_GEM"; }
        @Override public String name() { return type.getIcon() + " " + quality.name + " " + type.getName() + " Gemstone"; }
        @Override public Material material() { return Material.PLAYER_HEAD; }
        @Override public Rarity rarity() { return quality.rarity; }
        @Override public String skin() { return Utils.texture(TEXT.get(id()).texture()); }
        @Override public SpecificItemType specificItemType() { return SpecificItemType.GEMSTONE; }
        @Override public List<String> categories() { return List.of("Collection Item"); }
        @Override public double npcSellPrice() { return quality.sellPrice; }

        @Override
        public List<String> lore() {
            List<String> lore = new ArrayList<>(TEXT.get(id()).intro());
            lore.add("");
            lore.add("&7Some say that when &eharnessed");
            lore.add("&eproperly&7, it can give its owner extra");
            lore.add(STAT.get(type) + "&7.");
            return lore;
        }
    }
}
